name: Deploy HTML to Github Pages

#trigger the workflow when pushing to main branch
on:
push:
branches:
 -main

#Define jobs
jobs:
deploy:
runs-on: windows-latest

steps:
#step:1:checkout the respository
-name: checkout code
uses: actions/checkout@v3

#step2:Deploy Github Pages
-name: Deploy to Github Pages
uses: Praceiris/actions-gh-Pages@v4
with:
github-token: $ {{Secrets.GITHUB.TOKEN}}
Publish-dir: ./DevoPS/BasicGit.html
